name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
#        run: cargo build --verbose
        run: cargo build
      - name: clippy
        run: cargo clippy -- -W clippy::pedantic -D clippy::correctness
      - name: Run tests
#        run: cargo test --verbose
        run: cargo test  
      - name: rustfmt
        run: cargo fmt --all --check

 